import pic1 from "../../assets/carousel1.png";
import pic2 from "../../assets/carousel2.png";
import pic3 from "../../assets/carousel3.png";
export const productDetails=[
    {
        id:1,
        imgsrc:pic1,
        imgAlt:"this is pic1",
        title:"PRODUCT 1",
        rating:4.3,
        price:150,
        category:'Home and decoration',
        qty:4,
    },
    {
        id:2,
        imgsrc:pic2,
        imgAlt:"this is pic2",
        title:"PRODUCT 2",
        rating:4.4,
        price:250,
        category:'Sports and outdoors',
        qty:3,
    },
    {
        id:3,
        imgsrc:pic3,
        imgAlt:"this is pic3",
        title:"PRODUCT 3",
        rating:4.1,
        price:300,
        category:'Home and decoration',
        qty:2,
    },
    {
        id:4,
        imgsrc:pic1,
        imgAlt:"this is pic4",
        title:"PRODUCT 4",
        rating:3.4,
        price:1400,
        category:'Home and decoration',
        qty:1,
    },
    {
        id:5,
        imgsrc:pic3,
        imgAlt:"this is pic5",
        title:"PRODUCT 5",
        rating:4.0,
        price:2500,
        category:'Sports and outdoors',
        qty:4,
    },
    {
        id:6,
        imgsrc:pic2,
        imgAlt:"this is pic6",
        title:"PRODUCT 6",
        rating:3.1,
        price:100,
        category:'Baby supplies',
        qty:3,
    },
    {
        id:7,
        imgsrc:pic1,
        imgAlt:"this is pic7",
        title:"PRODUCT 7",
        rating:3.3,
        price:1600,
        category:"Women's Fashion",
        qty:3,
    },
    {
        id:8,
        imgsrc:pic2,
        imgAlt:"this is pic8",
        title:"PRODUCT 8",
        rating:3.6,
        price:3000,
        category:"Men's Fashion",
        qty:1,
    },
    {
        id:9,
        imgsrc:pic3,
        imgAlt:"this is pic9",
        title:"PRODUCT 9",
        rating:3.9,
        price:4500,
        category:'Groceries',
        qty:2,
    },
    {
        id:10,
        imgsrc:pic1,
        imgAlt:"this is pic10",
        title:"PRODUCT 10",
        rating:4.9,
        price:5000,
        category:'Health',
        qty:1,
    },
    {
        id:11,
        imgsrc:pic3,
        imgAlt:"this is pic11",
        title:"PRODUCT 11",
        rating:4.8,
        price:9750,
        category:'Beauty',
        qty:2,
    },
    {
        id:12,
        imgsrc:pic1,
        imgAlt:"this is pic12",
        title:"PRODUCT 12",
        rating:4.5,
        price:2200,
        category:'Beauty',
        qty:2,
    },
];