export const questions = [
  {
    id: 1,
    qn: "If I do not collect a payment voucher will I be able to place an order on D-Mart?",
    ans: "Yes. If a payment voucher is not collected, you will still be able to make a transaction/prepayment, however, a bank or wallet discount will not be applied.",
    category: "Voucher Information",
  },
  {
    id: 2,
    qn: "How do I use a Voucher?",
    ans: " Vouchers are promotional offers that often provide discounts on future purchases during specific campaigns or events on the platform.",
    category: "Voucher Information",
  },
  {
    id: 3,
    qn: "What is the validity of vouchers?",
    ans: "You can check the validity of the Voucher under the Voucher detail.",
    category: "Voucher Information",
  },
  {
    id: 4,
    qn: "How can I learn more about the upcoming campaigns and the discounts?",
    ans: "We usually come up with amazing deals and promotional offers for our customers to enjoy. We encourage you to stay updated on the D-Mart platform so you do not miss out on any exciting offers in future.",
    category: "Campaigns",
  },
  {
    id: 5,
    qn: "Are there any offers for a new user?",
    ans: "D-Mart has brought an exciting offer for new users. New users can collect collectible vouchers and redeem them on their very first purchase. The voucher is applicable on the D-Mart App only.",
    category: "Campaigns",
  },
  {
    id: 6,
    qn: "My  app is not working. What should I do?",
    ans: "At times, the D-Mart app might not work due to certain reasons.",
    category: "Privacy & Security",
  },
  {
    id: 7,
    qn: "I believe someone has logged in to my account and placed the order, what should I do?",
    ans: "It is highly advisable to not share your Login Credentials with anyone. If you feel that someone has logged into your account and placed the order, please reach out to us via live chat. We will look into it and facilitate you at the earliest.",
    category: "Privacy & Security",
  },
  {
    id: 8,
    qn: "What is the Buyer Policy?",
    ans: "We are committed to building a trusted and reliable platform for our community and the Buyer Policy ensures that D-Mart operates in a safe and orderly manner, with the aim of creating a pleasant shopping experience for all user.",
    category: "Privacy & Security",
  },
  {
    id: 9,
    qn: "How do I create an account?",
    ans: "To create an account, navigate to the website's homepage and look for the 'Sign Up' option.Fill in your details such as name, email address, and create a password. Once completed, you'll typically receive a confirmation email to verify your account.",
    category: "My Account",
  },
  {
    id: 10,
    qn: "What should I do if I forget my password?",
    ans: "If you forget your password, click on the 'Forgot Password' link on the login page. You'll be asked to enter your email address, and then instructions will be sent to your email on how to reset your password. ",
    category: "My Account",
  },
  {
    id: 11,
    qn: "How can I delete my account?",
    ans: "To delete your account, please reach out to our customer support team. They will guide you through the account deletion process and ensure that all your personal data is removed securely from our systems.",
    category: "My Account",
  },
  {
    id: 12,
    qn: "What payment methods are accepted on the website?",
    ans: "We accept various payment methods like eSewa, and Cash on delivery.",
    category: "Payment Method",
  },
  {
    id: 13,
    qn: "What happens if my payment fails or is declined?",
    ans: "If a payment fails or is declined, double-check the payment details entered. You may also contact your bank or try an alternative payment method.",
    category: "Payment Method",
  },
  {
    id: 14,
    qn: "Is it safe to make online payments on this website?",
    ans: "Yes, our website uses secure payment gateways and encryption to protect your financial information, ensuring safe transactions.",
    category: "Payment Method",
  },
  {
    id: 15,
    qn: "What is express delivery?",
    ans: "Express delivery is a faster shipping option that ensures your order is delivered within a shorter timeframe compared to standard delivery.",
    category: "D-Mart Express",
  },
  {
    id: 16,
    qn: "Is express delivery available for all products?",
    ans: "Express delivery may be available for select products or locations. Check the product details or during checkout for express delivery options.",
    category: "D-Mart Express",
  },
  {
    id: 17,
    qn: "Is there an extra charge for express delivery?",
    ans: "Yes, express delivery often incurs an additional fee due to the faster shipping service. The cost varies based on the weight, size, and destination of the package.",
    category: "D-Mart Express",
  },
  {
    id: 18,
    qn: "How do I select express delivery for my order?",
    ans: "During the checkout process, choose the express delivery option if available. This may be listed alongside shipping options and costs.",
    category: "D-Mart Express",
  },
  {
    id: 19,
    qn: "What are pick-up points?",
    ans: "Pick-up points are designated locations where customers can collect their online orders instead of opting for home delivery.",
    category: "D-Mart Pick Up Points",
  },
  {
    id: 20,
    qn: "How do I select a pick-up point for my order?",
    ans: "Pick-up points may be available for certain orders and specific locations. Check during checkout or product details for pick-up point options.",
    category: "D-Mart Pick Up Points",
  },
  {
    id: 21,
    qn: "How can I find the nearest pick-up point to my location?",
    ans: "The website usually provides a list of available pick-up points with addresses or maps. You can select the one closest to you during checkout.",
    category: "D-Mart Pick Up Points",
  },
  {
    id: 22,
    qn: "What is the estimated delivery time for my order?",
    ans: "Estimated delivery times vary based on the shipping method and destination. Typically, it ranges from a few days to a couple of weeks within Nepal.",
    category: "Shipping Journey",
  },
  {
    id: 23,
    qn: "What happens if I'm not available to receive the package?",
    ans: "The courier service may attempt delivery multiple times. If unsuccessful, they might leave a notice or contact you for further instructions or redelivery.",
    category: "Shipping Journey",
  },
  {
    id: 2,
    qn: "Are there shipping charges for my order?",
    ans: "Shipping charges may apply and vary based on factors like weight, destination, and chosen delivery method. These charges are usually shown during checkout.",
    category: "Shipping Journey",
  },
  {
    id: 25,
    qn: "How can I identify 'D-mart Verified' products or sellers?",
    ans: "Look for a badge, label, or specific designation that indicates the 'D-mart Verified' status on the product or seller profile.",
    category: "D-Mart Verified",
  },
  {
    id: 26,
    qn: "Can I trust products or sellers labeled as 'D-mart Verified'?",
    ans: "'D-mart Verified' products or sellers undergo a verification process, offering a higher level of trust. However, it's recommended to read customer reviews and research before making a purchase.",
    category: "D-Mart Verified",
  },
  {
    id: 27,
    qn: "How can a seller or product get 'D-mart Verified' status?",
    ans: "Sellers or products might need to meet specific criteria or standards set by D-mart, undergo verification checks, or comply with certain guidelines to attain the 'D-mart Verified' status.",
    category: "D-Mart Verified",
  },
  {
    id: 28,
    qn: "What is the timeframe for requesting a refund?",
    ans: "Typically, customers need to request a refund within a specified period after receiving the product or canceling the order.",
    category: "Refund Policy",
  },
  {
    id: 29,
    qn: "What items are eligible for a refund?",
    ans: "Eligibility for a refund usually depends on the condition of the returned item and adherence to the website's specific return criteria.",
    category: "Refund Policy",
  },
  {
    id: 30,
    qn: "How do I initiate a refund?",
    ans: "Customers can usually initiate a refund request through their account on the website or by contacting customer support.",
    category: "Refund Policy",
  },
  {
    id: 31,
    qn: "Can I get a full refund, including shipping charges?",
    ans: "Refund policies may vary, but some websites refund the entire amount including shipping charges, while others might deduct shipping fees.",
    category: "Refund Policy",
  },
  {
    id: 32,
    qn: "How long is the warranty period for products?",
    ans: "Warranty periods vary by product and brand. Check the product details or warranty information provided for the specific duration.",
    category: "Warranty Policy",
  },
  {
    id: 33,
    qn: "What does the warranty cover?",
    ans: "Warranties typically cover manufacturing defects or malfunctions occurring under normal use conditions. It may vary depending on the product.",
    category: "Warranty Policy",
  },
  {
    id: 34,
    qn: "How do I claim warranty service?",
    ans: "To claim warranty service, contact customer support or follow the procedure outlined in the warranty policy for guidance on initiating a claim.",
    category: "Warranty Policy",
  },
  {
    id: 35,
    qn: "How do I initiate a return?",
    ans: "Customers can usually initiate a return request through their account on the website or by contacting customer support.",
    category: "Return Process",
  },
  {
    id: 36,
    qn: "Is there a return shipping fee?",
    ans: "Return shipping fees might be borne by the customer or waived, depending on the reason for the return and the website's policy.",
    category: "Return Process",
  },
  {
    id: 37,
    qn: "Are there conditions for returning an item?",
    ans: "Items generally need to be in their original condition, with tags intact and packaging undamaged, to be eligible for return.",
    category: "Return Process",
  },
  {
    id: 38,
    qn: "What is the timeframe for initiating a return?",
    ans: "Typically, customers need to initiate a return request within a specified period after receiving the product.",
    category: "Return Process",
  },
  {
    id: 39,
    qn: "How long does the refund process take?",
    ans: "Refund processing times vary, but typically, once the returned item is received, refunds are processed within a few business days.",
    category: "Refund Process",
  },
  {
    id: 40,
    qn: "How will I receive my refund?",
    ans: "Refunds are generally issued through the original payment method used during the purchase.",
    category: "Refund Process",
  },
  {
    id: 41,
    qn: "What if I haven't received my refund within the expected timeframe?",
    ans: "If there's a delay in receiving your refund, contact customer support for assistance in tracking the refund status.",
    category: "Refund Process",
  },
  {
    id: 42,
    qn: "What if I paid with a different payment method than I currently have?",
    ans: "Refunds are usually processed back to the original payment method used during the purchase. Contact customer support for assistance if the payment method has changed.",
    category: "Refund Process",
  },
  {
    id: 43,
    qn: "How can I become a seller on the ecommerce website?",
    ans: "To become a seller, usually, you need to create a seller account by registering on the website's seller portal.",
    category: "Become Seller",
  },
  {
    id: 44,
    qn: "How do I upload or list my products for sale on the website?",
    ans: "Sellers typically use the seller dashboard or interface provided by the website to create product listings with details like descriptions, images, and pricing.",
    category: "Become Seller",
  },
  {
    id: 45,
    qn: "Are there any performance metrics or criteria for sellers to meet?",
    ans: "D-Mart  have performance metrics like seller ratings or sales targets for maintaining seller status. Familiarize yourself with the platform's seller guidelines.",
    category: "Become Seller",
  },
  {
    id: 46,
    qn: "How can I contact seller support?",
    ans: "Sellers can usually contact seller support through dedicated helplines, email, live chat, or seller support portals provided by the ecommerce website.",
    category: "Seller Support",
  },
  {
    id: 47,
    qn: "What are the working hours of seller support?",
    ans: "Seller support typically operates during business hours specified by the ecommerce platform, and some may offer 24/7 assistance for urgent issues.",
    category: "Seller Support",
  },
  {
    id: 48,
    qn: "How long does it take for seller support to respond to queries?",
    ans: "Response times vary but often aim to address queries within a specified timeframe, usually within 24-48 hours.",
    category: "Seller Support",
  },
  {
    id: 49,
    qn: "Are there charges for using seller support services?",
    ans: "seller support services are provided by the ecommerce website without additional charges.",
    category: "Seller Support",
  },
];
